server:
        port: 7777
spring:
        datasource:
                url: jdbc:h2:mem:accounts
                username: sa
                password: 
                initialization-mode: always
                initialize: true
                
